### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by jmsv** [jmsv/simple-mern#2]
see https://github.com/jmsv/simple-mern#extend-simple-mern

Let me know if you're interested in working on this and I'll make a target branch for the PR 🙂

**Comment by alejandrotoga02** [comment]
@jmsv I would like to take it! :D

**Comment by jmsv** [comment]
Cool, I've set up a target branch for the PR: [`with-docker`](https://github.com/jmsv/simple-mern/tree/with-docker)

**Comment by alejandrotoga02** [comment]
@jmsv Thanks
