### ISSUE TITLE
Add React Router

### ISSUE THREAD

**Issue by jmsv** [jmsv/simple-mern#4]
see https://github.com/jmsv/simple-mern#extend-simple-mern

Let me know if you're interested in working on this and I'll make a target branch for the PR 🙂

**Comment by leonlafa** [comment]
Happy to jump on this 😁

**Comment by jmsv** [comment]
@leonlafa go for it!

**Comment by leonlafa** [comment]
I've implemented and tested the router, works as expected.   Do you want me to leave app structure as is or split into pages?

**Comment by leonlafa** [comment]
I also need a target branch to push to 😁

**Comment by jmsv** [comment]
sorted :+1: [`with-react-router`](https://github.com/jmsv/simple-mern/tree/with-react-router)

**Comment by jmsv** [comment]
done in #12
