### ISSUE TITLE
Add global state management with Redux/MobX

### ISSUE THREAD

**Issue by jmsv** [jmsv/simple-mern#5]
see https://github.com/jmsv/simple-mern#extend-simple-mern

Let me know if you're interested in working on this and I'll make a target branch for the PR 🙂

**Comment by rahulSinha-01** [comment]
Hey @jmsv Can I start working on this?

**Comment by jmsv** [comment]
@rahulSinha-01 Sure! do you want to add Redux or MobX?

**Comment by rahulSinha-01** [comment]
Redux

**Comment by jmsv** [comment]
Awesome, when you create the PR please target the [`with-redux`](https://github.com/jmsv/simple-mern/tree/with-redux) branch

**Comment by rahulSinha-01** [comment]
ok

**Comment by rahulSinha-01** [comment]
I have only store the tasks on to the redux store. Can I now make pull request?

**Comment by rahulSinha-01** [comment]
And I have also included redux dev tool integration code, should I let it remain in the code or remove it?

**Comment by jmsv** [comment]
@rahulSinha-01 Go for it :rocket: We can keep the devtools integration

**Comment by rahulSinha-01** [comment]
ok good to know

**Comment by jmsv** [comment]
closed in #17
