### ISSUE TITLE
Replace fetch with axios for requests

### ISSUE THREAD

**Issue by jmsv** [jmsv/simple-mern#6]
see https://github.com/jmsv/simple-mern#extend-simple-mern

Let me know if you're interested in working on this and I'll make a target branch for the PR 🙂

**Comment by leonlafa** [comment]
Hello!  React is my least practised framework, so I would love to help out and get my hands dirty with some React.  I can create an API service that spins up a default instance of Axios,  other services/components will then be able to extend from it.  I'm happy to create an example service and component to show this workflow. 

Let me know if you like the idea or had something else in mind 😁

**Comment by jmsv** [comment]
Awesome, reusable axios instance sounds good 😄

**Comment by leonlafa** [comment]
Brilliant!  Assign me please and ill jump onto it tomorrow eve  😃

**Comment by leonlafa** [comment]
Any particular strategy for branch name and pull requests?

**Comment by jmsv** [comment]
Extensions to simple-mern will be in branches and then listed on the README - I've set up the [`with-axios`](https://github.com/jmsv/simple-mern/tree/with-axios) branch for this PR to target

**Comment by leonlafa** [comment]
I've done the swap 😁, Axios is now in the client, however, I've had to implement some cors stuff in the backend to overcome a cors issue.    

How do you want me to approach this,  do you want me to raise this as bug/issue and address this before pushing this work?

**Comment by jmsv** [comment]
shouldn't need to add CORS in backend - the frontend has a proxy specified: https://github.com/jmsv/simple-mern/blob/master/client/package.json#L5

**Comment by leonlafa** [comment]
Using Axios in place of fetch does create aa cors error.  I'll do some digging and see why that might be

**Comment by jmsv** [comment]
are you setting a `baseURL` or something?

**Comment by leonlafa** [comment]
> are you setting a `baseURL` or something?

Yeah ill try without it, if you're using the proxy thing

**Comment by leonlafa** [comment]
Just to clarify, that was the issue.  👍

**Comment by jmsv** [comment]
closed in #9
