### ISSUE TITLE
Add UI framework

### ISSUE THREAD

**Issue by jmsv** [jmsv/simple-mern#7]
Using, for example:

- Ant Design
- Material UI
- reactstrap

---

see https://github.com/jmsv/simple-mern#extend-simple-mern

Let me know if you're interested in working on this and I'll make a target branch for the PR 🙂

**Comment by leonlafa** [comment]
I'm happy to add Material UI.   It might need some refactoring though once all other branches are merged into master

**Comment by leonlafa** [comment]
I'm ready for a target branch 😁

**Comment by jmsv** [comment]
Go for it 😀 No need to worry about the merge - the point of this repo is to keep `master` as minimal as possible, and other things people might want to add are in branches and linked from the readme

**Comment by leonlafa** [comment]
> Go for it 😀 No need to worry about the merge - the point of this repo is to keep `master` as minimal as possible, and other things people might want to add are in branches and linked from the readme

Ah yeah, I get you 👍.

**Comment by jmsv** [comment]
done in #13
